let symbolArray = [
  { key: "Esc", altkey: None, ruKey: "Esc", ruAltKey: None },
  { key: "F1", altkey: None, ruKey: "F1", ruAltKey: None },
  { key: "F2", altkey: None, ruKey: "F2", ruAltKey: None },
  { key: "F3", altkey: None, ruKey: "F3", ruAltKey: None },
  { key: "F4", altkey: None, ruKey: "F4", ruAltKey: None },
  { key: "F5", altkey: None, ruKey: "F5", ruAltKey: None },
  { key: "F6", altkey: None, ruKey: "F6", ruAltKey: None },
  { key: "F7", altkey: None, ruKey: "F7", ruAltKey: None },
  { key: "F8", altkey: None, ruKey: "F8", ruAltKey: None },
  { key: "`", altKey: "~", ruKey: "ё", ruAltKey: "Ё" },
  { key: "1", altKey: "!", ruKey: "1", ruAltKey: "!" },
  { key: "2", altKey: "@", ruKey: "2", ruAltKey: '"' },
  { key: "3", altKey: "#", ruKey: "3", ruAltKey: "№" },
  { key: "4", altKey: "$", ruKey: "4", ruAltKey: ";" },
  { key: "5", altKey: "%", ruKey: "5", ruAltKey: "%" },
  { key: "6", altKey: "^", ruKey: "6", ruAltKey: ":" },
  { key: "7", altKey: "&", ruKey: "7", ruAltKey: "?" },
  { key: "8", altKey: "*", ruKey: "8", ruAltKey: "*" },
  { key: "9", altKey: "(", ruKey: "9", ruAltKey: "(" },
  { key: "0", altKey: ")", ruKey: "0", ruAltKey: ")" },
  { key: "-", altKey: "_", ruKey: "-", ruAltKey: "_" },
  { key: "=", altKey: "+", ruKey: "+", ruAltKey: None },
  { key: "Backspace", altKey: None, ruKey: "Backspace", ruAltKey: None },
  { key: "Tab", altKey: None, ruKey: "Tab", ruAltKey: None },
  { key: "Q", altKey: None, ruKey: "Й", ruAltKey: None },
  { key: "W", altKey: None, ruKey: "Ц", ruAltKey: None },
  { key: "E", altKey: None, ruKey: "У", ruAltKey: None },
  { key: "R", altKey: None, ruKey: "К", ruAltKey: None },
  { key: "T", altKey: None, ruKey: "Е", ruAltKey: None },
  { key: "Y", altKey: None, ruKey: "Н", ruAltKey: None },
  { key: "U", altKey: None, ruKey: "Г", ruAltKey: None },
  { key: "I", altKey: None, ruKey: "Ш", ruAltKey: None },
  { key: "O", altKey: None, ruKey: "Щ", ruAltKey: None },
  { key: "P", altKey: None, ruKey: "З", ruAltKey: None },
  { key: "[", altKey: "{", ruKey: "Х", ruAltKey: None },
  { key: "]", altKey: "}", ruKey: "Ъ", ruAltKey: None },
  { key: "\\", altKey: "|", ruKey: "\\", ruAltKey: "/" },
  { key: "Caps Lock", altKey: None, ruKey: "Caps Lock", ruAltKey: None },
  { key: "A", altKey: None, ruKey: "Ф", ruAltKey: None },
  { key: "S", altKey: None, ruKey: "Ы", ruAltKey: None },
  { key: "D", altKey: None, ruKey: "В", ruAltKey: None },
  { key: "F", altKey: None, ruKey: "А", ruAltKey: None },
  { key: "G", altKey: None, ruKey: "П", ruAltKey: None },
  { key: "H", altKey: None, ruKey: "Р", ruAltKey: None },
  { key: "J", altKey: None, ruKey: "О", ruAltKey: None },
  { key: "K", altKey: None, ruKey: "Л", ruAltKey: None },
  { key: "L", altKey: None, ruKey: "Д", ruAltKey: None },
  { key: ";", altKey: ":", ruKey: "Ж", ruAltKey: None },
  { key: "'", altKey: '"', ruKey: "Э", ruAltKey: None },
  { key: "Enter", altKey: None, ruKey: "Enter", ruAltKey: None },
  { key: "Shift", altKey: None, ruKey: "Shift", ruAltKey: None },
  { key: "Z", altKey: None, ruKey: "Я", ruAltKey: None },
  { key: "X", altKey: None, ruKey: "Ч", ruAltKey: None },
  { key: "C", altKey: None, ruKey: "С", ruAltKey: None },
  { key: "V", altKey: None, ruKey: "М", ruAltKey: None },
  { key: "B", altKey: None, ruKey: "И", ruAltKey: None },
  { key: "N", altKey: None, ruKey: "Т", ruAltKey: None },
  { key: "M", altKey: None, ruKey: "Ь", ruAltKey: None },
  { key: "\\<", altKey: "\\>", ruKey: "Б", ruAltKey: None },
  { key: "\\.", altKey: "\\>", ruKey: "Ю", ruAltKey: None },
  { key: "\\/", altKey: "\\?", ruKey: ".", ruAltKey: "," },
  { key: "Shift", altKey: None, ruKey: "Shift", ruAltKey: None },
  { key: "Ctrl", altKey: None, ruKey: "Ctrl", ruAltKey: None },
  { key: "Fn", altKey: None, ruKey: "Fn", ruAltKey: None },
  { key: "Windows", altKey: None, ruKey: "Windows", ruAltKey: None },
  { key: "Alt", altKey: None, ruKey: "Alt", ruAltKey: None },
  { key: "Spacebar", altKey: None, ruKey: "Spacebar", ruAltKey: None },
  { key: "Alt", altKey: None, ruKey: "Alt", ruAltKey: None },
  { key: "Ctrl", altKey: None, ruKey: "Ctrl", ruAltKey: None },
  { key: "Left Arrow", altKey: None, ruKey: "Left Arrow", ruAltKey: None },
  { key: "Up Arrow", altKey: None, ruKey: "Up Arrow", ruAltKey: None },
  { key: "Down Arrow", altKey: None, ruKey: "Down Arrow", ruAltKey: None },
  { key: "Right Arrow", altKey: None, ruKey: "Right Arrow", ruAltKey: None },
];
